dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-10

script:
  - CXX=/usr/bin/g++-10 CC=/usr/bin/gcc-10 cmake -Bbuild
  - cmake --build build --config Release --parallel 4