// Copyright (c) zpc contributors. Licensed under the MIT License.
// ZpcReflectRuntime.hpp — Lightweight runtime reflection types consumed by
// the code generated by zpc_reflect_tool.
//
// This header is always included by generated `.reflected.hpp` files.
// It provides the core data structures (TypeInfo, FieldInfo, MethodInfo, …)
// and the compile-time / runtime helpers that generated code fills in.
//
// This header is std-free — it only depends on ZpcMeta.hpp and C headers.

#pragma once

#include "zensim/ZpcMeta.hpp"

namespace zs {
namespace reflect {

  // -----------------------------------------------------------------------
  // Type identifiers
  // -----------------------------------------------------------------------

  /// Simple enum to categorize primitive and common types in metadata.
  enum class TypeId : zs::u8 {
    Unknown = 0,
    Bool,
    Int8,
    Uint8,
    Int16,
    Uint16,
    Int32,
    Uint32,
    Int64,
    Uint64,
    Float,
    Double,
    String,
    Enum,
    Pointer,
    Reference,
    Array,
    Record,  // struct / class / union
    Void,
  };

  // -----------------------------------------------------------------------
  // Access specifiers (matching clang::AccessSpecifier)
  // -----------------------------------------------------------------------

  enum class Access : zs::u8 {
    Public = 0,
    Protected,
    Private,
    None,
  };

  // -----------------------------------------------------------------------
  // Metadata — arbitrary key-value pairs attached to declarations
  // -----------------------------------------------------------------------

  /// A single metadata entry.  Both key and value are string literals
  /// (or pointers into static storage) — no ownership or allocation.
  struct MetaEntry {
    const char* key;
    const char* value;  ///< stored as string; callers interpret as needed.
  };

  // -----------------------------------------------------------------------
  // Field descriptor
  // -----------------------------------------------------------------------

  struct FieldInfo {
    const char*      name;              ///< Field name.
    const char*      typeName;          ///< Canonical C++ type name.
    zs::u64          typeHash{0};       ///< FNV-1a hash of the canonical type name.
    TypeId           typeId{TypeId::Unknown};
    Access           access{Access::Public};
    zs::size_t       offset{0};         ///< offsetof()
    zs::size_t       size{0};           ///< sizeof()
    bool             isPointer{false};
    bool             isReference{false};
    bool             isConst{false};
    bool             isStatic{false};
    bool             isTransient{false};     ///< Excluded from serialization.
    bool             isSerializable{true};   ///< Included in serialization.
    const MetaEntry* metadata{nullptr};
    int              metadataCount{0};
  };

  // -----------------------------------------------------------------------
  // Method descriptor
  // -----------------------------------------------------------------------

  struct ParamInfo {
    const char* name;
    const char* typeName;
    bool        hasDefault{false};
    const char* defaultExpr{nullptr};  ///< Stringified default expression.
  };

  struct MethodInfo {
    const char*      name;
    const char*      returnType;
    const ParamInfo* params{nullptr};
    int              paramCount{0};
    Access           access{Access::Public};
    bool             isStatic{false};
    bool             isConst{false};
    bool             isVirtual{false};
    bool             isPureVirtual{false};
    bool             isNoexcept{false};
    const MetaEntry* metadata{nullptr};
    int              metadataCount{0};
  };

  // -----------------------------------------------------------------------
  // Base class descriptor
  // -----------------------------------------------------------------------

  struct BaseInfo {
    const char* name;
    zs::u64     typeHash{0};
    Access      access{Access::Public};
    bool        isVirtual{false};
  };

  // -----------------------------------------------------------------------
  // Enum value descriptor
  // -----------------------------------------------------------------------

  struct EnumValueInfo {
    const char*      name;
    zs::i64          value{0};
    const MetaEntry* metadata{nullptr};
    int              metadataCount{0};
  };

  // -----------------------------------------------------------------------
  // TypeInfo — the main descriptor for a reflected type
  // -----------------------------------------------------------------------

  /// @note All pointer members refer to static-storage arrays emitted by
  /// the code generator; no dynamic memory is involved.
  struct TypeInfo {
    const char*          name{nullptr};          ///< Qualified C++ name.
    const char*          displayName{nullptr};   ///< Short, editor-friendly name.
    zs::u64              typeHash{0};            ///< FNV-1a hash.
    zs::size_t           size{0};                ///< sizeof(T).
    zs::size_t           align{0};               ///< alignof(T).
    bool                 isClass{false};
    bool                 isStruct{false};
    bool                 isUnion{false};
    bool                 isEnum{false};
    bool                 isAbstract{false};
    bool                 isAggregate{false};
    const FieldInfo*     fields{nullptr};
    int                  fieldCount{0};
    const MethodInfo*    methods{nullptr};
    int                  methodCount{0};
    const BaseInfo*      bases{nullptr};
    int                  baseCount{0};
    const EnumValueInfo* enumValues{nullptr};    ///< Non-empty only for enums.
    int                  enumValueCount{0};
    const MetaEntry*     metadata{nullptr};
    int                  metadataCount{0};

    /// Find a field by name.  Returns nullptr if not found.
    const FieldInfo* findField(const char* n) const {
      if (!n || !fields) return nullptr;
      for (int i = 0; i < fieldCount; ++i) {
        const char* a = fields[i].name;
        const char* b = n;
        while (*a && *a == *b) { ++a; ++b; }
        if (*a == *b) return &fields[i];
      }
      return nullptr;
    }

    /// Find a method by name.  Returns nullptr if not found (first overload).
    const MethodInfo* findMethod(const char* n) const {
      if (!n || !methods) return nullptr;
      for (int i = 0; i < methodCount; ++i) {
        const char* a = methods[i].name;
        const char* b = n;
        while (*a && *a == *b) { ++a; ++b; }
        if (*a == *b) return &methods[i];
      }
      return nullptr;
    }
  };

  // -----------------------------------------------------------------------
  // Compile-time type-info accessor (specialized by generated code)
  // -----------------------------------------------------------------------

  /// Primary template — not reflected.
  template <typename T, typename = void>
  struct TypeInfoOf {
    static constexpr bool reflected = false;
  };

  /// Helper to test whether a type has reflection data.
  template <typename T>
  inline constexpr bool is_reflected_v = TypeInfoOf<zs::remove_cvref_t<T>>::reflected;

  /// Convenience accessor.  Returns nullptr for non-reflected types.
  template <typename T>
  inline const TypeInfo* type_info() {
    if constexpr (is_reflected_v<T>) {
      return &TypeInfoOf<zs::remove_cvref_t<T>>::get();
    } else {
      return nullptr;
    }
  }

  // -----------------------------------------------------------------------
  // FNV-1a hash (matches the reflect tool)
  // -----------------------------------------------------------------------

  namespace detail {
    /// Null-safe C string comparison (avoids <cstring> dependency).
    inline bool str_eq(const char* a, const char* b) noexcept {
      if (a == b) return true;
      if (!a || !b) return false;
      while (*a && *a == *b) { ++a; ++b; }
      return *a == *b;
    }

    /// FNV-1a hash over a null-terminated C string.
    inline constexpr zs::u64 fnv1a_64(const char* s) noexcept {
      zs::u64 h = 0xcbf29ce484222325ULL;
      if (s) {
        for (; *s; ++s) {
          h ^= static_cast<unsigned char>(*s);
          h *= 0x100000001b3ULL;
        }
      }
      return h;
    }
  }  // namespace detail

}  // namespace reflect
}  // namespace zs
