// Copyright (c) zpc contributors. Licensed under the MIT License.
// Example: Using zpc reflection annotations.
//
// This file demonstrates how to annotate C++ types for automatic
// clang-based reflection.  When processed by zpc_reflect_tool,
// a corresponding `.reflected.hpp` file is generated containing
// compile-time and runtime type metadata.
//
// Build integration:
//   In your CMakeLists.txt, after defining your target:
//
//     add_library(my_lib src/MyCode.cpp)
//     target_link_libraries(my_lib PRIVATE zpc)
//     zpc_target_reflect_sources(my_lib
//       SOURCES
//         include/MyReflectedTypes.hpp
//       INCLUDE_DIRS
//         ${CMAKE_CURRENT_SOURCE_DIR}/include
//     )
//
//   Then in your .cpp file:
//     #include "reflect/my_lib/MyReflectedTypes.reflected.hpp"
//     // Now you can query zs::reflect::TypeInfoOf<MyStruct>::get()

#pragma once

#include <string>
#include <vector>
#include <zensim/reflect/ZpcReflectAnnotations.hpp>
#include <zensim/reflect/ZpcReflectObject.hpp>

// ========================================================================
// 1. Basic struct reflection
// ========================================================================

namespace example {

  /// A simple reflected struct. All public fields are collected.
  struct ZS_REFLECT Transform {
    ZS_PROPERTY(name = "position", tooltip = "World-space position")
    float x{0.0f}, y{0.0f}, z{0.0f};

    ZS_PROPERTY(name = "rotation", tooltip = "Euler angles in degrees")
    float rx{0.0f}, ry{0.0f}, rz{0.0f};

    ZS_PROPERTY(name = "scale")
    float sx{1.0f}, sy{1.0f}, sz{1.0f};

    ZS_NO_REFLECT  // excluded from reflection
    int _dirty_flag{0};
  };

  // ========================================================================
  // 2. Inheritance
  // ========================================================================

  struct ZS_REFLECT Node {
    ZS_PROPERTY(name = "id")
    int id{0};

    ZS_PROPERTY(name = "name")
    std::string name;

    ZS_METHOD(category = "lifecycle")
    virtual void update(float dt) {}

    virtual ~Node() = default;
  };

  struct ZS_REFLECT MeshNode : public Node {
    ZS_PROPERTY(name = "vertex_count")
    int vertexCount{0};

    ZS_SERIALIZE
    std::vector<float> vertices;

    ZS_METHOD(category = "render")
    void draw() const {}
  };

  // ========================================================================
  // 3. Enum reflection
  // ========================================================================

  enum class ZS_REFLECT_ENUM RenderMode {
    Solid    = 0,
    Wireframe = 1,
    Points    = 2,
  };

  // ========================================================================
  // 4. Traits
  // ========================================================================

  struct ZS_REFLECT ZS_TRAIT(kind = "Serializable", version = 2)
  SaveData {
    ZS_FIELD(serializable = true)
    std::string filename;

    ZS_FIELD(serializable = true)
    int version{1};

    ZS_FIELD(transient = true)
    void* runtimeCache{nullptr};
  };

  // ========================================================================
  // 5. Object-based reflected type — runtime member access & method calling
  // ========================================================================
  //
  //   By inheriting from zs::reflect::Object, a type gains virtual
  //   getField() / setField() / invoke() that work by name at runtime:
  //
  //     example::Particle p;
  //     p.setField("mass", zs::reflect::Any(2.0f));
  //     float m = p.getField("mass").as<float>();
  //     zs::reflect::Any args[] = {
  //         zs::reflect::Any(0.f), zs::reflect::Any(-9.8f), zs::reflect::Any(0.f)
  //     };
  //     p.invoke("applyForce", args, 3);
  //
  //   This also works WITHOUT inheriting from Object via free functions:
  //     zs::reflect::setField(p, "mass", zs::reflect::Any(2.0f));

  struct ZS_REFLECT Particle : public zs::reflect::Object {
    ZS_PROPERTY(name = "position_x") float px{0.f};
    ZS_PROPERTY(name = "position_y") float py{0.f};
    ZS_PROPERTY(name = "position_z") float pz{0.f};

    ZS_PROPERTY(name = "mass") float mass{1.0f};

    ZS_METHOD(category = "physics")
    void applyForce(float fx, float fy, float fz) {
      px += fx / mass;
      py += fy / mass;
      pz += fz / mass;
    }

    ZS_METHOD(category = "physics")
    float kineticEnergy() const { return 0.5f * mass * (px*px + py*py + pz*pz); }

    // --- Object interface (generated by the reflect tool via AccessorOf) ---
    // These must be implemented by the user when inheriting Object.
    // A convenience macro ZS_OBJECT_BODY could automate this; for now manual:
    const zs::reflect::TypeInfo& typeInfo() const override {
      return zs::reflect::TypeInfoOf<Particle>::get();
    }
    const zs::reflect::Accessor& accessor() const override {
      return zs::reflect::AccessorOf<Particle>::get();
    }
  };

  // ========================================================================
  // 6. Non-Object reflected type — standalone field access & invocation
  // ========================================================================
  //
  //   Types that do NOT inherit from Object can still be accessed at runtime
  //   via the free-function API and the Accessor:
  //
  //     example::Light light;
  //     zs::reflect::setField(light, "intensity", zs::reflect::Any(0.8f));
  //     auto val = zs::reflect::getField(light, "intensity"); // Any(0.8f)
  //     auto* acc = zs::reflect::accessor_of<example::Light>();
  //     zs::reflect::Any ret;
  //     acc->invoke(&light, "turnOff", nullptr, 0, &ret);

  struct ZS_REFLECT Light {
    ZS_PROPERTY(name = "intensity") float intensity{1.0f};
    ZS_PROPERTY(name = "color_r")   float r{1.0f};
    ZS_PROPERTY(name = "color_g")   float g{1.0f};
    ZS_PROPERTY(name = "color_b")   float b{1.0f};

    ZS_METHOD(category = "control")
    void turnOff() { intensity = 0.f; }

    ZS_METHOD(category = "control")
    void setColor(float nr, float ng, float nb) { r = nr; g = ng; b = nb; }
  };

  // ========================================================================
  // 7. Python bindings usage
  // ========================================================================
  //
  //   When built with PYTHON_BINDINGS, all reflected types above get:
  //     - extern "C" create/destroy functions
  //     - Per-field typed getter/setter (primitive types go directly,
  //       complex types as opaque void*)
  //     - Per-method C-ABI invokers
  //     - A generated Python module with ctypes wrappers
  //
  //   CMakeLists.txt:
  //     zpc_target_reflect_sources(my_lib
  //       SOURCES include/reflect_example.hpp
  //       PYTHON_BINDINGS
  //       PYTHON_LIB_NAME my_lib_reflect_py
  //     )
  //
  //   Python:
  //     from my_lib_reflect import Particle, Light, RenderMode
  //     p = Particle()
  //     p.mass = 2.0
  //     p.applyForce(1.0, -9.8, 0.0)
  //     print(p.px, p.py, p.pz)
  //     print(Particle._field_names())
  //     del p

} // namespace example
