// Copyright (c) zpc contributors. Licensed under the MIT License.
#include "codegen.hpp"
#include "parser.hpp"              // CollectedType, ReflectionModel
#include "zensim/zpc_tpls/fmt/format.h"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <variant>

namespace zs::reflect_tool {

  // -----------------------------------------------------------------------
  // Helpers for code-gen strings
  // -----------------------------------------------------------------------

  static std::string escape_string(std::string_view s) {
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
      if (c == '"')  out += "\\\"";
      else if (c == '\\') out += "\\\\";
      else if (c == '\n') out += "\\n";
      else out += c;
    }
    return out;
  }

  static std::string access_enum(std::string_view s) {
    if (s == "public")    return "::zs::reflect::Access::Public";
    if (s == "protected") return "::zs::reflect::Access::Protected";
    if (s == "private")   return "::zs::reflect::Access::Private";
    return "::zs::reflect::Access::None";
  }

  /// Convert a MetadataContainer property value to a C string literal.
  static std::string meta_value_literal(const MetaValue& v) {
    std::string valStr;
    std::visit([&](auto&& arg) {
      using T = std::decay_t<decltype(arg)>;
      if constexpr (std::is_same_v<T, std::string>)
        valStr = fmt::format("\"{}\"", escape_string(arg));
      else if constexpr (std::is_same_v<T, int>)
        valStr = fmt::format("\"{}\"", arg);
      else if constexpr (std::is_same_v<T, float>)
        valStr = fmt::format("\"{}\"", arg);
      else if constexpr (std::is_same_v<T, std::vector<std::string>>) {
        valStr = "\"";
        for (size_t i = 0; i < arg.size(); ++i) {
          if (i) valStr += ",";
          valStr += escape_string(arg[i]);
        }
        valStr += "\"";
      } else if constexpr (std::is_same_v<T, std::vector<float>>) {
        valStr = "\"";
        for (size_t i = 0; i < arg.size(); ++i) {
          if (i) valStr += ",";
          valStr += fmt::format("{}", arg[i]);
        }
        valStr += "\"";
      } else {
        valStr = "\"\"";
      }
    }, v);
    return valStr;
  }

  /// Emit a static MetaEntry array for the given metadata container.
  static void emit_meta_array(std::ostringstream& os,
                               const std::string& arrayName,
                               const MetadataContainer& meta) {
    os << fmt::format("static const ::zs::reflect::MetaEntry {}[] = {{\n",
                      arrayName);
    for (auto& [k, v] : meta.properties) {
      os << fmt::format("  {{R\"({})\", {}}},\n", k, meta_value_literal(v));
    }
    os << "};\n";
  }

  // -----------------------------------------------------------------------
  // emit_reflected_header — per-source generated header
  // -----------------------------------------------------------------------

  void emit_reflected_header(const std::string& outputPath,
                             const std::vector<CollectedType>& types,
                             bool verbose) {
    std::ostringstream os;

    os << "// ============================================================\n"
       << "// Auto-generated by zpc_reflect_tool — DO NOT EDIT\n"
       << "// ============================================================\n"
       << "#pragma once\n"
       << "#include <zensim/reflect/ZpcReflectRuntime.hpp>\n"
       << "#include <zensim/reflect/ZpcReflectRegistry.hpp>\n"
       << "#include <zensim/reflect/ZpcReflectObject.hpp>\n\n";

    // Forward declarations
    for (auto& ct : types) {
      if (!ct.forwardDecl.empty()) os << ct.forwardDecl;
    }
    os << "\n";

    // TypeInfoOf specializations
    for (auto& ct : types) {
      const std::string varName = convert_to_valid_cpp_var_name(ct.qualifiedName);

      // ================================================================
      // Phase 1: emit static arrays that will be referenced by TypeInfo
      // ================================================================

      // --- Per-field metadata arrays ---
      for (size_t fi = 0; fi < ct.fields.size(); ++fi) {
        auto& f = ct.fields[fi];
        if (f.metadata.properties.empty()) continue;
        emit_meta_array(os, fmt::format("_zs_fmeta_{}_{}", varName, f.name),
                        f.metadata);
      }

      // --- Per-method param arrays and metadata arrays ---
      {
        std::unordered_map<std::string, int> nameCount;
        for (auto& m : ct.methods) {
          int idx = nameCount[m.name]++;
          std::string mSuffix = idx > 0 ? fmt::format("_{}", idx) : "";

          if (!m.params.empty()) {
            os << fmt::format(
                "static const ::zs::reflect::ParamInfo _zs_mparams_{}_{}{}[] = {{\n",
                varName, m.name, mSuffix);
            for (auto& p : m.params) {
              os << fmt::format("  {{R\"({})\", R\"({})\", {}, {}}},\n",
                                p.name, p.typeName,
                                p.hasDefault ? "true" : "false",
                                p.hasDefault ? fmt::format("R\"({})\"", escape_string(p.defaultExpr)) : "nullptr");
            }
            os << "};\n";
          }
          if (!m.metadata.properties.empty()) {
            emit_meta_array(os,
                fmt::format("_zs_mmeta_{}_{}{}", varName, m.name, mSuffix),
                m.metadata);
          }
        }
      }

      // --- FieldInfo array ---
      if (!ct.fields.empty()) {
        os << fmt::format(
            "static const ::zs::reflect::FieldInfo _zs_ti_fields_{}[] = {{\n",
            varName);
        for (auto& f : ct.fields) {
          std::string typeIdStr = "::zs::reflect::TypeId::Unknown";
          if (f.typeName == "bool" || f.typeName == "_Bool")
            typeIdStr = "::zs::reflect::TypeId::Bool";
          else if (f.typeName == "unsigned char" || f.typeName == "uint8_t")
            typeIdStr = "::zs::reflect::TypeId::Uint8";
          else if (f.typeName == "char" || f.typeName == "signed char" || f.typeName == "int8_t")
            typeIdStr = "::zs::reflect::TypeId::Int8";
          else if (f.typeName == "short" || f.typeName == "signed short" || f.typeName == "int16_t")
            typeIdStr = "::zs::reflect::TypeId::Int16";
          else if (f.typeName == "unsigned short" || f.typeName == "uint16_t")
            typeIdStr = "::zs::reflect::TypeId::Uint16";
          else if (f.typeName == "int" || f.typeName == "signed int" || f.typeName == "int32_t")
            typeIdStr = "::zs::reflect::TypeId::Int32";
          else if (f.typeName == "unsigned int" || f.typeName == "uint32_t")
            typeIdStr = "::zs::reflect::TypeId::Uint32";
          else if (f.typeName == "long long" || f.typeName == "signed long long" || f.typeName == "int64_t")
            typeIdStr = "::zs::reflect::TypeId::Int64";
          else if (f.typeName == "unsigned long long" || f.typeName == "uint64_t")
            typeIdStr = "::zs::reflect::TypeId::Uint64";
          else if (f.typeName == "float")
            typeIdStr = "::zs::reflect::TypeId::Float";
          else if (f.typeName == "double")
            typeIdStr = "::zs::reflect::TypeId::Double";
          else if (f.typeName.find("string") != std::string::npos)
            typeIdStr = "::zs::reflect::TypeId::String";
          else if (f.isPointer) typeIdStr = "::zs::reflect::TypeId::Pointer";
          else if (f.isReference) typeIdStr = "::zs::reflect::TypeId::Reference";
          else typeIdStr = "::zs::reflect::TypeId::Record";

          bool isTransient = false;
          bool isSerializable = true;
          for (auto& [mk, mv] : f.metadata.properties) {
            if (mk == "transient") {
              if (auto* s = std::get_if<std::string>(&mv); s && *s == "true")
                isTransient = true;
            }
            if (mk == "serializable") {
              if (auto* s = std::get_if<std::string>(&mv); s && *s == "false")
                isSerializable = false;
            }
          }

          std::string metaRef = "nullptr";
          std::string metaCnt = "0";
          if (!f.metadata.properties.empty()) {
            metaRef = fmt::format("_zs_fmeta_{}_{}", varName, f.name);
            metaCnt = fmt::format("{}", f.metadata.properties.size());
          }

          os << fmt::format(
              "  {{R\"({})\", R\"({})\", 0x{:016X}ULL, {}, {},"
              " {}, {}, {}, {}, {}, {}, {}, {}, {}, {}}},\n",
              f.name, f.typeNameNoTag, f.typeHash, typeIdStr,
              access_enum(f.accessStr),
              f.offset, f.size,
              f.isPointer ? "true" : "false",
              f.isReference ? "true" : "false",
              f.isConst ? "true" : "false",
              f.isStatic ? "true" : "false",
              isTransient ? "true" : "false",
              isSerializable ? "true" : "false",
              metaRef, metaCnt);
        }
        os << "};\n";
      }

      // --- MethodInfo array ---
      if (!ct.methods.empty()) {
        os << fmt::format(
            "static const ::zs::reflect::MethodInfo _zs_ti_methods_{}[] = {{\n",
            varName);
        std::unordered_map<std::string, int> nameCount2;
        for (auto& m : ct.methods) {
          int idx = nameCount2[m.name]++;
          std::string mSuffix = idx > 0 ? fmt::format("_{}", idx) : "";

          std::string paramsRef = "nullptr";
          std::string paramsCnt = "0";
          if (!m.params.empty()) {
            paramsRef = fmt::format("_zs_mparams_{}_{}{}", varName, m.name, mSuffix);
            paramsCnt = fmt::format("{}", m.params.size());
          }

          std::string metaRef = "nullptr";
          std::string metaCnt = "0";
          if (!m.metadata.properties.empty()) {
            metaRef = fmt::format("_zs_mmeta_{}_{}{}", varName, m.name, mSuffix);
            metaCnt = fmt::format("{}", m.metadata.properties.size());
          }

          os << fmt::format(
              "  {{R\"({})\", R\"({})\", {}, {}, {}, {}, {}, {}, {}, {}, {}, {}}},\n",
              m.name, m.returnType,
              paramsRef, paramsCnt,
              access_enum(m.accessStr),
              m.isStatic ? "true" : "false",
              m.isConst ? "true" : "false",
              m.isVirtual ? "true" : "false",
              m.isPureVirtual ? "true" : "false",
              m.isNoexcept ? "true" : "false",
              metaRef, metaCnt);
        }
        os << "};\n";
      }

      // --- BaseInfo array ---
      if (!ct.bases.empty()) {
        os << fmt::format(
            "static const ::zs::reflect::BaseInfo _zs_ti_bases_{}[] = {{\n",
            varName);
        for (auto& b : ct.bases) {
          os << fmt::format("  {{R\"({})\", 0x{:016X}ULL, {}, {}}},\n",
                            b.nameNoTag, b.typeHash, access_enum(b.accessStr),
                            b.isVirtual ? "true" : "false");
        }
        os << "};\n";
      }

      // --- EnumValueInfo array ---
      if (!ct.enumValues.empty()) {
        // Per-enum-value metadata
        for (size_t evi = 0; evi < ct.enumValues.size(); ++evi) {
          auto& ev = ct.enumValues[evi];
          if (ev.metadata.properties.empty()) continue;
          emit_meta_array(os, fmt::format("_zs_evmeta_{}_{}", varName, ev.name),
                          ev.metadata);
        }

        os << fmt::format(
            "static const ::zs::reflect::EnumValueInfo _zs_ti_enums_{}[] = {{\n",
            varName);
        for (auto& ev : ct.enumValues) {
          std::string metaRef = "nullptr";
          std::string metaCnt = "0";
          if (!ev.metadata.properties.empty()) {
            metaRef = fmt::format("_zs_evmeta_{}_{}", varName, ev.name);
            metaCnt = fmt::format("{}", ev.metadata.properties.size());
          }
          os << fmt::format("  {{R\"({})\", {}LL, {}, {}}},\n",
                            ev.name, ev.value, metaRef, metaCnt);
        }
        os << "};\n";
      }

      // --- Type-level metadata ---
      if (!ct.metadata.properties.empty()) {
        emit_meta_array(os, fmt::format("_zs_ti_meta_{}", varName),
                        ct.metadata);
      }

      os << "\n";

      // ================================================================
      // Phase 2: emit TypeInfoOf specialization
      // ================================================================

      os << "// ---- " << ct.qualifiedName << " ----\n";
      os << "template <>\n";
      os << fmt::format("struct ::zs::reflect::TypeInfoOf<{}> {{\n", ct.nameNoTag);
      os << "  static constexpr bool reflected = true;\n\n";
      os << "  static const ::zs::reflect::TypeInfo& get() {\n";
      os << "    static const ::zs::reflect::TypeInfo info = {\n";
      os << fmt::format("      /* name        */ R\"({})\",\n", ct.qualifiedName);
      os << fmt::format("      /* displayName */ R\"({})\",\n", ct.displayName);
      os << fmt::format("      /* typeHash    */ 0x{:016X}ULL,\n", ct.typeHash);
      os << fmt::format("      /* size        */ {},\n", ct.size);
      os << fmt::format("      /* align       */ {},\n", ct.align);
      os << fmt::format("      /* isClass     */ {},\n", ct.isClass ? "true" : "false");
      os << fmt::format("      /* isStruct    */ {},\n", ct.isStruct ? "true" : "false");
      os << fmt::format("      /* isUnion     */ {},\n", ct.isUnion ? "true" : "false");
      os << fmt::format("      /* isEnum      */ {},\n", ct.isEnum ? "true" : "false");
      os << fmt::format("      /* isAbstract  */ {},\n", ct.isAbstract ? "true" : "false");
      os << fmt::format("      /* isAggregate */ {},\n", ct.isAggregate ? "true" : "false");

      // fields pointer + count
      os << fmt::format("      /* fields      */ {}, {},\n",
          ct.fields.empty() ? "nullptr" : fmt::format("_zs_ti_fields_{}", varName),
          ct.fields.size());

      // methods pointer + count
      os << fmt::format("      /* methods     */ {}, {},\n",
          ct.methods.empty() ? "nullptr" : fmt::format("_zs_ti_methods_{}", varName),
          ct.methods.size());

      // bases pointer + count
      os << fmt::format("      /* bases       */ {}, {},\n",
          ct.bases.empty() ? "nullptr" : fmt::format("_zs_ti_bases_{}", varName),
          ct.bases.size());

      // enumValues pointer + count
      os << fmt::format("      /* enumValues  */ {}, {},\n",
          ct.enumValues.empty() ? "nullptr" : fmt::format("_zs_ti_enums_{}", varName),
          ct.enumValues.size());

      // type metadata pointer + count
      os << fmt::format("      /* metadata    */ {}, {}\n",
          ct.metadata.properties.empty() ? "nullptr" : fmt::format("_zs_ti_meta_{}", varName),
          ct.metadata.properties.size());

      os << "    };\n";
      os << "    return info;\n";
      os << "  }\n";
      os << "};\n\n";

      // Static auto-registration
      os << fmt::format(
          "static const ::zs::reflect::AutoRegister _zs_autoreg_{}"
          "(& ::zs::reflect::TypeInfoOf<{}>::get());\n\n",
          varName, ct.nameNoTag);

      // ---- AccessorOf specialization (static function pointers + flat arrays) ----
      if (!ct.isEnum) {
        // Count accessible fields and methods
        int accessibleFieldCount = 0;
        for (auto& f : ct.fields) {
          if (!f.isStatic) ++accessibleFieldCount;
        }
        int accessibleMethodCount = 0;
        for (auto& m : ct.methods) {
          if (m.accessStr == "public" && !m.isPureVirtual) ++accessibleMethodCount;
        }

        // ---- Static getter functions ----
        for (auto& f : ct.fields) {
          if (f.isStatic) continue;
          os << fmt::format(
              "static void _zs_get_{0}_{1}(const void* obj, ::zs::reflect::Any* out) {{\n"
              "  *out = ::zs::reflect::Any(static_cast<const {2}*>(obj)->{1});\n"
              "}}\n",
              varName, f.name, ct.nameNoTag);
        }

        // ---- Static setter functions (skip const fields) ----
        for (auto& f : ct.fields) {
          if (f.isStatic || f.isConst) continue;
          os << fmt::format(
              "static void _zs_set_{0}_{1}(void* obj, const ::zs::reflect::Any* val) {{\n"
              "  static_cast<{2}*>(obj)->{1} = val->as<{3}>();\n"
              "}}\n",
              varName, f.name, ct.nameNoTag, f.typeNameNoTag);
        }

        // ---- Static method invoker functions ----
        struct MethodFuncEntry { std::string name; std::string funcName; };
        std::vector<MethodFuncEntry> methodEntries;
        {
          std::unordered_map<std::string, int> overloadIdx;
          for (auto& m : ct.methods) {
            if (m.accessStr != "public") continue;
            if (m.isPureVirtual) continue;

            int idx = overloadIdx[m.name]++;
            std::string suffix = idx > 0 ? fmt::format("_{}", idx) : "";
            std::string funcName = fmt::format("_zs_invoke_{0}_{1}{2}", varName, m.name, suffix);

            bool isVoidReturn = (m.returnType == "void");

            // Build the call expression
            std::string callExpr;
            if (m.isStatic) {
              callExpr = fmt::format("{}::{}", ct.nameNoTag, m.name);
            } else if (m.isConst) {
              callExpr = fmt::format(
                  "static_cast<const {}*>(obj)->{}", ct.nameNoTag, m.name);
            } else {
              callExpr = fmt::format(
                  "static_cast<{}*>(obj)->{}", ct.nameNoTag, m.name);
            }

            // Build parameter list
            std::string paramList;
            for (size_t pi = 0; pi < m.params.size(); ++pi) {
              if (pi > 0) paramList += ", ";
              paramList += fmt::format("args[{}].as<{}>()", pi, m.params[pi].typeName);
            }

            os << fmt::format(
                "static void {}(void* obj, const ::zs::reflect::Any* args,"
                " int nargs, ::zs::reflect::Any* ret) {{\n",
                funcName);

            if (isVoidReturn) {
              os << fmt::format("  {}({});\n"
                                "  (void)ret; (void)args; (void)nargs;\n",
                                callExpr, paramList);
            } else {
              os << fmt::format("  auto _r = {}({});\n"
                                "  if (ret) *ret = ::zs::reflect::Any(_r);\n"
                                "  (void)args; (void)nargs;\n",
                                callExpr, paramList);
            }
            os << "}\n";

            methodEntries.push_back({m.name, funcName});
          }
        }

        os << "\n";

        // ---- Static field accessor array ----
        if (accessibleFieldCount > 0) {
          os << fmt::format(
              "static const ::zs::reflect::FieldAccessor _zs_fields_{}[] = {{\n",
              varName);
          for (auto& f : ct.fields) {
            if (f.isStatic) continue;
            std::string setFn = f.isConst
                ? "nullptr"
                : fmt::format("&_zs_set_{}_{}", varName, f.name);
            os << fmt::format("  {{\"{}\", &_zs_get_{}_{}, {}}},\n",
                              f.name, varName, f.name, setFn);
          }
          os << "};\n\n";
        }

        // ---- Static method accessor array ----
        if (accessibleMethodCount > 0) {
          os << fmt::format(
              "static const ::zs::reflect::MethodAccessor _zs_methods_{}[] = {{\n",
              varName);
          for (auto& me : methodEntries) {
            os << fmt::format("  {{\"{}\", &{}}},\n", me.name, me.funcName);
          }
          os << "};\n\n";
        }

        // ---- AccessorOf template specialization ----
        os << fmt::format(
            "template <>\n"
            "struct ::zs::reflect::AccessorOf<{}> {{\n"
            "  static constexpr bool available = true;\n\n"
            "  static const ::zs::reflect::Accessor& get() {{\n"
            "    static const ::zs::reflect::Accessor acc = {{\n"
            "      &::zs::reflect::TypeInfoOf<{}>::get(),\n"
            "      {}, {},\n"
            "      {}, {}\n"
            "    }};\n"
            "    return acc;\n"
            "  }}\n"
            "}};\n\n",
            ct.nameNoTag, ct.nameNoTag,
            accessibleFieldCount > 0
                ? fmt::format("_zs_fields_{}", varName) : "nullptr",
            accessibleFieldCount,
            accessibleMethodCount > 0
                ? fmt::format("_zs_methods_{}", varName) : "nullptr",
            accessibleMethodCount);

        // Auto-register the accessor
        os << fmt::format(
            "static const ::zs::reflect::AutoRegisterAccessor _zs_accreg_{}"
            "(0x{:016X}ULL, &::zs::reflect::AccessorOf<{}>::get());\n\n",
            varName, ct.typeHash, ct.nameNoTag);
      }
    }

    // Write to file
    std::ofstream ofs(outputPath, std::ios::out | std::ios::trunc);
    if (!ofs) {
      std::cerr << fmt::format("Cannot write generated header: {}\n", outputPath);
      return;
    }
    ofs << os.str();
    if (verbose)
      fmt::print("  Wrote {} type(s) → {}\n", types.size(), outputPath);
  }

  // -----------------------------------------------------------------------
  // emit_register_source — aggregated registration .cpp
  // -----------------------------------------------------------------------

  void emit_register_source(const std::string& outputPath,
                            const ReflectionModel& model,
                            const CodeCompilerState& state,
                            const std::string& targetName,
                            bool verbose) {
    std::ostringstream os;

    os << "// ============================================================\n"
       << "// Auto-generated by zpc_reflect_tool — DO NOT EDIT\n"
       << "// Target: " << targetName << "\n"
       << "// ============================================================\n"
       << "#include <zensim/reflect/ZpcReflectRegistry.hpp>\n\n";

    // Include original source files so reflected types are complete definitions
    for (auto& src : model.inputSourcePaths) {
      os << fmt::format("#include \"{}\"\n", src);
    }
    os << "\n";

    // Include all generated per-source headers
    for (auto& h : model.generatedHeaders) {
      os << fmt::format("#include \"{}\"\n", h);
    }
    os << "\n";

    // A registration function that can be called explicitly if needed
    os << fmt::format(
        "namespace zs::reflect::generated_{} {{\n"
        "  void register_all_types() {{\n"
        "    // Types are auto-registered via static initializers in\n"
        "    // the included generated headers.  This function exists\n"
        "    // so that users can force the linker to pull in the TU.\n"
        "  }}\n"
        "}} // namespace zs::reflect::generated_{}\n",
        targetName, targetName);

    // Ensure output directory exists
    auto parentDir = std::filesystem::path(outputPath).parent_path();
    if (!parentDir.empty()) mkdirs(parentDir.string());

    std::ofstream ofs(outputPath, std::ios::out | std::ios::trunc);
    if (!ofs) {
      std::cerr << fmt::format("Cannot write registration source: {}\n", outputPath);
      return;
    }
    ofs << os.str();
    if (verbose)
      fmt::print("  Wrote registration source → {}\n", outputPath);
  }

  // -----------------------------------------------------------------------
  // Python C-ABI helpers
  // -----------------------------------------------------------------------

  /// Map a C++ type name to a string for the ctypes return/param type.
  /// Returns the C type we will use in the extern "C" function signature.
  static std::string cpp_to_c_type(const std::string& typeName) {
    // Normalize: strip const, &, *, whitespace for matching
    std::string t = typeName;
    // Remove leading/trailing whitespace
    while (!t.empty() && t.front() == ' ') t.erase(t.begin());
    while (!t.empty() && t.back() == ' ')  t.pop_back();

    if (t == "void")      return "void";
    if (t == "bool")      return "bool";
    if (t == "int8_t"  || t == "char" || t == "signed char") return "int8_t";
    if (t == "int16_t" || t == "short")    return "int16_t";
    if (t == "int32_t" || t == "int")      return "int32_t";
    if (t == "int64_t" || t == "long long") return "int64_t";
    // NOTE: C++ 'long' is 4 bytes on Windows (MSVC/LLP64) but 8 bytes on
    // most Unix (LP64).  Since the reflect tool uses Clang (which follows
    // the host ABI), we map 'long' based on the platform that will load
    // the generated bindings.  Using int32_t on Windows is the safe default.
#ifdef _MSC_VER
    if (t == "long") return "int32_t";
#else
    if (t == "long") return "int64_t";
#endif
    if (t == "uint8_t" || t == "unsigned char") return "uint8_t";
    if (t == "uint16_t"|| t == "unsigned short") return "uint16_t";
    if (t == "uint32_t"|| t == "unsigned int" || t == "unsigned") return "uint32_t";
    if (t == "uint64_t"|| t == "unsigned long long") return "uint64_t";
#ifdef _MSC_VER
    if (t == "unsigned long") return "uint32_t";
#else
    if (t == "unsigned long") return "uint64_t";
#endif
    if (t == "float")     return "float";
    if (t == "double")    return "double";
    if (t.find("string") != std::string::npos) return "const char*";
    return ""; // empty → not a simple C type, use void* / skip
  }

  /// Map C type to Python ctypes name.
  static std::string c_type_to_ctypes(const std::string& ctype) {
    if (ctype == "void")        return "None";
    if (ctype == "bool")        return "ctypes.c_bool";
    if (ctype == "int8_t")      return "ctypes.c_int8";
    if (ctype == "int16_t")     return "ctypes.c_int16";
    if (ctype == "int32_t")     return "ctypes.c_int32";
    if (ctype == "int64_t")     return "ctypes.c_int64";
    if (ctype == "uint8_t")     return "ctypes.c_uint8";
    if (ctype == "uint16_t")    return "ctypes.c_uint16";
    if (ctype == "uint32_t")    return "ctypes.c_uint32";
    if (ctype == "uint64_t")    return "ctypes.c_uint64";
    if (ctype == "float")       return "ctypes.c_float";
    if (ctype == "double")      return "ctypes.c_double";
    if (ctype == "const char*") return "ctypes.c_char_p";
    if (ctype == "void*")       return "ctypes.c_void_p";
    return "ctypes.c_void_p";
  }

  /// Return true if the C++ field type can be directly mapped to a C type.
  static bool is_simple_c_type(const std::string& typeName) {
    return !cpp_to_c_type(typeName).empty();
  }

  /// Sanitize a C++ qualified name to be safe for C function names.
  static std::string sanitize_for_c(const std::string& name) {
    std::string out;
    for (char c : name) {
      if (c == ':' || c == '<' || c == '>' || c == ',' || c == ' ')
        out += '_';
      else
        out += c;
    }
    // collapse consecutive underscores
    std::string collapsed;
    for (char c : out) {
      if (c == '_' && !collapsed.empty() && collapsed.back() == '_') continue;
      collapsed += c;
    }
    return collapsed;
  }

  // -----------------------------------------------------------------------
  // emit_python_bindings — per-target C-ABI source
  // -----------------------------------------------------------------------

  void emit_python_bindings(const std::string& outputPath,
                            const std::vector<CollectedType>& allTypes,
                            const std::string& targetName,
                            bool verbose) {
    std::ostringstream os;

    os << "// ============================================================\n"
       << "// Auto-generated by zpc_reflect_tool — DO NOT EDIT\n"
       << "// Python ctypes C-ABI bindings for target: " << targetName << "\n"
       << "// ============================================================\n"
       << "#include <zensim/reflect/ZpcReflectPyExport.hpp>\n"
       << "#include <zensim/reflect/ZpcReflectObject.hpp>\n"
       << "#include <cstdint>\n"
       << "#include <cstring>\n"
       << "#include <string>\n\n";

    // We need the actual type declarations — include the user headers
    // that were processed. For now emit a comment; the CMake integration
    // will add the proper include path / generated headers.
    os << "// User type headers are expected to be available via includes.\n"
       << "// Make sure -I paths or pre-includes are set correctly.\n\n";

    for (auto& ct : allTypes) {
      if (ct.isEnum) continue;       // enums get introspection, not create/destroy
      if (ct.isAbstract) continue;   // can't instantiate abstract types

      std::string safeName = sanitize_for_c(ct.qualifiedName);
      std::unordered_map<std::string, int> overloadCounters; // per-type, reset each iteration

      // ---- create / destroy ----
      os << fmt::format(
          "// ---- {} ----\n"
          "ZPC_REFLECT_PY_API void* zs_reflect_{}_create() {{\n"
          "  return static_cast<void*>(new {});\n"
          "}}\n\n",
          ct.qualifiedName, safeName, ct.nameNoTag);

      os << fmt::format(
          "ZPC_REFLECT_PY_API void zs_reflect_{}_destroy(void* p) {{\n"
          "  delete static_cast<{}*>(p);\n"
          "}}\n\n",
          safeName, ct.nameNoTag);

      // ---- type_name ----
      os << fmt::format(
          "ZPC_REFLECT_PY_API const char* zs_reflect_{}_type_name() {{\n"
          "  return R\"({})\";\n"
          "}}\n\n",
          safeName, ct.qualifiedName);

      // ---- field names ----
      {
        std::string joined;
        for (size_t i = 0; i < ct.fields.size(); ++i) {
          if (i > 0) joined += ",";
          joined += ct.fields[i].name;
        }
        os << fmt::format(
            "ZPC_REFLECT_PY_API const char* zs_reflect_{}_field_names() {{\n"
            "  return \"{}\";\n"
            "}}\n\n",
            safeName, joined);
      }

      // ---- method names ----
      {
        std::string joined;
        bool first = true;
        for (auto& m : ct.methods) {
          if (m.accessStr != "public") continue;
          if (m.isPureVirtual) continue;
          if (!first) joined += ",";
          joined += m.name;
          first = false;
        }
        os << fmt::format(
            "ZPC_REFLECT_PY_API const char* zs_reflect_{}_method_names() {{\n"
            "  return \"{}\";\n"
            "}}\n\n",
            safeName, joined);
      }

      // ---- per-field getter / setter ----
      for (auto& f : ct.fields) {
        if (f.isStatic) continue;
        std::string ctype = cpp_to_c_type(f.typeNameNoTag);
        bool isString = (ctype == "const char*");
        bool isSimple = !ctype.empty();

        if (isSimple) {
          // Getter
          if (isString) {
            // std::string → const char*  (copy via thread-local buffer)
            os << fmt::format(
                "ZPC_REFLECT_PY_API const char* zs_reflect_{}_get_{}(void* p) {{\n"
                "  return ::zs::reflect::py::returnString("
                "static_cast<{}*>(p)->{}.c_str());\n"
                "}}\n\n",
                safeName, f.name, ct.nameNoTag, f.name);
          } else {
            os << fmt::format(
                "ZPC_REFLECT_PY_API {} zs_reflect_{}_get_{}(void* p) {{\n"
                "  return static_cast<{}*>(p)->{};\n"
                "}}\n\n",
                ctype, safeName, f.name, ct.nameNoTag, f.name);
          }

          // Setter (if not const)
          if (!f.isConst) {
            if (isString) {
              os << fmt::format(
                  "ZPC_REFLECT_PY_API void zs_reflect_{}_set_{}(void* p, const char* v) {{\n"
                  "  static_cast<{}*>(p)->{} = v ? v : \"\";\n"
                  "}}\n\n",
                  safeName, f.name, ct.nameNoTag, f.name);
            } else {
              os << fmt::format(
                  "ZPC_REFLECT_PY_API void zs_reflect_{}_set_{}(void* p, {} v) {{\n"
                  "  static_cast<{}*>(p)->{} = v;\n"
                  "}}\n\n",
                  safeName, f.name, ctype, ct.nameNoTag, f.name);
            }
          }
        } else {
          // Complex type: expose as void* (pointer to field in-place)
          os << fmt::format(
              "ZPC_REFLECT_PY_API void* zs_reflect_{}_get_{}_ptr(void* p) {{\n"
              "  return static_cast<void*>(&static_cast<{}*>(p)->{});\n"
              "}}\n\n",
              safeName, f.name, ct.nameNoTag, f.name);
        }
      }

      // ---- per-method invoker ----
      for (auto& m : ct.methods) {
        if (m.accessStr != "public") continue;
        if (m.isPureVirtual) continue;
        if (m.isStatic) continue;

        // Check if ALL params and return type are simple C types
        std::string retCType = cpp_to_c_type(m.returnType);
        bool retIsString = (retCType == "const char*");
        bool allSimple = !retCType.empty() || m.returnType == "void";
        std::vector<std::string> paramCTypes;
        for (auto& p : m.params) {
          std::string pc = cpp_to_c_type(p.typeName);
          paramCTypes.push_back(pc);
          if (pc.empty()) allSimple = false;
        }

        if (!allSimple) {
          // Skip methods with complex parameter types for direct C-ABI
          // They can still be called via the Accessor/Any interface.
          continue;
        }

        bool isVoidReturn = (m.returnType == "void");
        std::string retType = isVoidReturn ? "void" : retCType;
        if (retIsString) retType = "const char*";

        // Build parameter signature
        std::string paramSig = "void* p";
        std::string argPass;
        for (size_t pi = 0; pi < m.params.size(); ++pi) {
          std::string pCType = paramCTypes[pi];
          bool pIsString = (pCType == "const char*");
          paramSig += fmt::format(", {} a{}", pCType, pi);
          if (pi > 0) argPass += ", ";
          if (pIsString) {
            // Convert const char* → std::string
            argPass += fmt::format("std::string(a{} ? a{} : \"\")", pi, pi);
          } else {
            argPass += fmt::format("a{}", pi);
          }
        }

        // Disambiguate overloaded methods by appending a sequential index
        // to the generated C symbol (avoids duplicate-symbol linker errors).
        std::string funcKey = safeName + "_" + m.name;
        int overloadIdx = overloadCounters[funcKey]++;
        std::string funcSuffix = overloadIdx > 0 ? fmt::format("_{}", overloadIdx) : "";

        os << fmt::format(
            "ZPC_REFLECT_PY_API {} zs_reflect_{}_call_{}{}({}) {{\n",
            retType, safeName, m.name, funcSuffix, paramSig);

        std::string callExpr;
        if (m.isConst) {
          callExpr = fmt::format(
              "static_cast<const {}*>(p)->{}({})",
              ct.nameNoTag, m.name, argPass);
        } else {
          callExpr = fmt::format(
              "static_cast<{}*>(p)->{}({})",
              ct.nameNoTag, m.name, argPass);
        }

        if (isVoidReturn) {
          os << fmt::format("  {};\n", callExpr);
        } else if (retIsString) {
          os << fmt::format("  return ::zs::reflect::py::returnString(({}).c_str());\n",
                            callExpr);
        } else {
          os << fmt::format("  return {};\n", callExpr);
        }
        os << "}\n\n";
      }

      // ---- generic accessor through Any (fallback) ----
      os << fmt::format(
          "ZPC_REFLECT_PY_API bool zs_reflect_{}_has_field(const char* name) {{\n"
          "  if constexpr (::zs::reflect::has_accessor_v<{}>) {{\n"
          "    return ::zs::reflect::AccessorOf<{}>::get().hasField(name);\n"
          "  }}\n"
          "  return false;\n"
          "}}\n\n",
          safeName, ct.nameNoTag, ct.nameNoTag);

      os << fmt::format(
          "ZPC_REFLECT_PY_API bool zs_reflect_{}_has_method(const char* name) {{\n"
          "  if constexpr (::zs::reflect::has_accessor_v<{}>) {{\n"
          "    return ::zs::reflect::AccessorOf<{}>::get().hasMethod(name);\n"
          "  }}\n"
          "  return false;\n"
          "}}\n\n",
          safeName, ct.nameNoTag, ct.nameNoTag);
    }

    // Ensure output directory exists
    auto parentDir = std::filesystem::path(outputPath).parent_path();
    if (!parentDir.empty()) mkdirs(parentDir.string());

    std::ofstream ofs(outputPath, std::ios::out | std::ios::trunc);
    if (!ofs) {
      std::cerr << fmt::format("Cannot write Python bindings: {}\n", outputPath);
      return;
    }
    ofs << os.str();
    if (verbose)
      fmt::print("  Wrote Python C-ABI bindings ({} types) → {}\n",
                  allTypes.size(), outputPath);
  }

  // -----------------------------------------------------------------------
  // emit_python_wrapper — Python ctypes wrapper module
  // -----------------------------------------------------------------------

  void emit_python_wrapper(const std::string& outputPath,
                           const std::vector<CollectedType>& allTypes,
                           const std::string& libName,
                           bool verbose) {
    std::ostringstream os;

    os << "# ============================================================\n"
       << "# Auto-generated by zpc_reflect_tool — DO NOT EDIT\n"
       << "# Python ctypes wrapper for: " << libName << "\n"
       << "# ============================================================\n"
       << "import ctypes\n"
       << "import os\n"
       << "import sys\n"
       << "from pathlib import Path\n\n"
       << "def _find_library(name: str):\n"
       << "    \"\"\"Find and load the shared library.\"\"\"\n"
       << "    search_paths = [\n"
       << "        Path(__file__).parent,\n"
       << "        Path(__file__).parent / 'lib',\n"
       << "        Path(__file__).parent / '..',\n"
       << "    ]\n"
       << "    if sys.platform == 'win32':\n"
       << "        suffixes = ['.dll', '.pyd']\n"
       << "    elif sys.platform == 'darwin':\n"
       << "        suffixes = ['.dylib', '.so']\n"
       << "    else:\n"
       << "        suffixes = ['.so']\n"
       << "    \n"
       << "    for d in search_paths:\n"
       << "        for sfx in suffixes:\n"
       << "            p = d / (name + sfx)\n"
       << "            if p.exists():\n"
       << "                return ctypes.cdll.LoadLibrary(str(p))\n"
       << "    # Last resort: let the OS search\n"
       << "    return ctypes.cdll.LoadLibrary(name)\n\n"
       << "_lib = _find_library('" << libName << "')\n\n";

    for (auto& ct : allTypes) {
      if (ct.isEnum) continue;
      if (ct.isAbstract) continue;

      std::string safeName = sanitize_for_c(ct.qualifiedName);
      std::string pyClassName = ct.displayName;
      // Make sure pyClassName is a valid Python identifier
      for (char& c : pyClassName) {
        if (!std::isalnum(c) && c != '_') c = '_';
      }

      os << "class " << pyClassName << ":\n"
         << "    \"\"\"Reflected type: " << ct.qualifiedName << "\"\"\"\n\n"
         << "    _create = _lib.zs_reflect_" << safeName << "_create\n"
         << "    _create.restype = ctypes.c_void_p\n"
         << "    _create.argtypes = []\n\n"
         << "    _destroy = _lib.zs_reflect_" << safeName << "_destroy\n"
         << "    _destroy.restype = None\n"
         << "    _destroy.argtypes = [ctypes.c_void_p]\n\n"
         << "    def __init__(self, _ptr=None):\n"
         << "        if _ptr is not None:\n"
         << "            self._ptr = _ptr\n"
         << "            self._owned = False\n"
         << "        else:\n"
         << "            self._ptr = self._create()\n"
         << "            self._owned = True\n\n"
         << "    def __del__(self):\n"
         << "        if self._owned and self._ptr:\n"
         << "            self._destroy(self._ptr)\n"
         << "            self._ptr = None\n\n";

      // Properties for each field
      for (auto& f : ct.fields) {
        if (f.isStatic) continue;
        std::string ctype = cpp_to_c_type(f.typeNameNoTag);
        bool isString = (ctype == "const char*");
        bool isSimple = !ctype.empty();

        if (isSimple) {
          std::string ctypesPy = c_type_to_ctypes(ctype);

          // getter
          os << "    @property\n"
             << "    def " << f.name << "(self):\n"
             << "        fn = _lib.zs_reflect_" << safeName << "_get_" << f.name << "\n"
             << "        fn.restype = " << ctypesPy << "\n"
             << "        fn.argtypes = [ctypes.c_void_p]\n";
          if (isString) {
            os << "        val = fn(self._ptr)\n"
               << "        return val.decode('utf-8') if val else ''\n\n";
          } else {
            os << "        return fn(self._ptr)\n\n";
          }

          // setter (if not const)
          if (!f.isConst) {
            os << "    @" << f.name << ".setter\n"
               << "    def " << f.name << "(self, value):\n"
               << "        fn = _lib.zs_reflect_" << safeName << "_set_" << f.name << "\n"
               << "        fn.restype = None\n"
               << "        fn.argtypes = [ctypes.c_void_p, " << ctypesPy << "]\n";
            if (isString) {
              os << "        fn(self._ptr, value.encode('utf-8') if isinstance(value, str) else value)\n\n";
            } else {
              os << "        fn(self._ptr, value)\n\n";
            }
          }
        } else {
          // Complex type: expose raw pointer
          os << "    @property\n"
             << "    def " << f.name << "_ptr(self):\n"
             << "        fn = _lib.zs_reflect_" << safeName << "_get_" << f.name << "_ptr\n"
             << "        fn.restype = ctypes.c_void_p\n"
             << "        fn.argtypes = [ctypes.c_void_p]\n"
             << "        return fn(self._ptr)\n\n";
        }
      }

      // Methods
      for (auto& m : ct.methods) {
        if (m.accessStr != "public") continue;
        if (m.isPureVirtual || m.isStatic) continue;

        std::string retCType = cpp_to_c_type(m.returnType);
        bool isVoidReturn = (m.returnType == "void");
        bool allSimple = !retCType.empty() || isVoidReturn;
        std::vector<std::string> paramCTypes;
        for (auto& p : m.params) {
          std::string pc = cpp_to_c_type(p.typeName);
          paramCTypes.push_back(pc);
          if (pc.empty()) allSimple = false;
        }
        if (!allSimple) continue; // skip methods with complex types

        std::string retCtypes;
        if (isVoidReturn) retCtypes = "None";
        else retCtypes = c_type_to_ctypes(retCType);

        bool retIsString = (retCType == "const char*");

        // Build Python method
        std::string pyParams = "self";
        std::string pyArgs = "self._ptr";
        for (size_t pi = 0; pi < m.params.size(); ++pi) {
          pyParams += fmt::format(", {}", m.params[pi].name.empty()
                                             ? fmt::format("arg{}", pi)
                                             : m.params[pi].name);
          std::string argName = m.params[pi].name.empty()
                                    ? fmt::format("arg{}", pi)
                                    : m.params[pi].name;
          bool pIsString = (paramCTypes[pi] == "const char*");
          if (pIsString) {
            pyArgs += fmt::format(", {}.encode('utf-8') if isinstance({}, str) else {}",
                                  argName, argName, argName);
          } else {
            pyArgs += fmt::format(", {}", argName);
          }
        }

        // argtypes
        std::string argtypesList = "ctypes.c_void_p";
        for (auto& pc : paramCTypes) {
          argtypesList += ", " + c_type_to_ctypes(pc);
        }

        os << "    def " << m.name << "(" << pyParams << "):\n"
           << "        fn = _lib.zs_reflect_" << safeName << "_call_" << m.name << "\n"
           << "        fn.restype = " << retCtypes << "\n"
           << "        fn.argtypes = [" << argtypesList << "]\n";
        if (isVoidReturn) {
          os << "        fn(" << pyArgs << ")\n\n";
        } else if (retIsString) {
          os << "        val = fn(" << pyArgs << ")\n"
             << "        return val.decode('utf-8') if val else ''\n\n";
        } else {
          os << "        return fn(" << pyArgs << ")\n\n";
        }
      }

      // Introspection helpers
      os << "    @staticmethod\n"
         << "    def _type_name():\n"
         << "        fn = _lib.zs_reflect_" << safeName << "_type_name\n"
         << "        fn.restype = ctypes.c_char_p\n"
         << "        fn.argtypes = []\n"
         << "        val = fn()\n"
         << "        return val.decode('utf-8') if val else ''\n\n"
         << "    @staticmethod\n"
         << "    def _field_names():\n"
         << "        fn = _lib.zs_reflect_" << safeName << "_field_names\n"
         << "        fn.restype = ctypes.c_char_p\n"
         << "        fn.argtypes = []\n"
         << "        val = fn()\n"
         << "        return (val.decode('utf-8') if val else '').split(',')\n\n"
         << "    @staticmethod\n"
         << "    def _method_names():\n"
         << "        fn = _lib.zs_reflect_" << safeName << "_method_names\n"
         << "        fn.restype = ctypes.c_char_p\n"
         << "        fn.argtypes = []\n"
         << "        val = fn()\n"
         << "        return (val.decode('utf-8') if val else '').split(',')\n\n"
         << "    def __repr__(self):\n"
         << "        return f'" << pyClassName << "({self._ptr:#x})'\n\n\n";
    }

    // Enum wrapper classes
    for (auto& ct : allTypes) {
      if (!ct.isEnum) continue;
      std::string pyClassName = ct.displayName;
      for (char& c : pyClassName) {
        if (!std::isalnum(c) && c != '_') c = '_';
      }

      os << "class " << pyClassName << ":\n"
         << "    \"\"\"Reflected enum: " << ct.qualifiedName << "\"\"\"\n";
      for (auto& ev : ct.enumValues) {
        os << "    " << ev.name << " = " << ev.value << "\n";
      }
      os << "\n\n";
    }

    // Ensure output directory exists
    auto parentDir = std::filesystem::path(outputPath).parent_path();
    if (!parentDir.empty()) mkdirs(parentDir.string());

    std::ofstream ofs(outputPath, std::ios::out | std::ios::trunc);
    if (!ofs) {
      std::cerr << fmt::format("Cannot write Python wrapper: {}\n", outputPath);
      return;
    }
    ofs << os.str();
    if (verbose)
      fmt::print("  Wrote Python wrapper → {}\n", outputPath);
  }

} // namespace zs::reflect_tool
